version: '3.8'

services:
  customer-service:
    build: ./services/customer-service
    container_name: customer-container
    ports:
        - "3000:3000"

  payment-service:
    build: ./services/payment-service
    container_name: payment-container
    ports:
        - "3001:3000"

  notification-service:
    build: ./services/notification-service
    container_name: notification-container
    ports:
        - "3002:3000"
